### ISSUE TITLE
suggest_able and self.bots[url_botname]["bot"]["hasSuggestedReplies"] KeyError: 'hasSuggestedReplies'

### ISSUE THREAD

**Issue by asce0** [canxin121/Async-Poe-Client#12]
suggest_able and self.bots[url_botname]["bot"]["hasSuggestedReplies"]
KeyError: 'hasSuggestedReplies'

**Comment by asce0** [comment]
when i tried to make the suggest_able = None, i got into Too much error when sending query issue like in #10

**Comment by asce0** [comment]
@canxin121 any help ?

**Comment by canxin121** [comment]
> @canxin121 any help ?
what is the url_botname?

**Comment by asce0** [comment]
GPT 4

**Comment by canxin121** [comment]
check your p_b and form key. And try using other bots

**Comment by asce0** [comment]
everything was working fine and suddenly it gets this error, the p_b and the form key are correct

**Comment by canxin121** [comment]
what about other bots?

**Comment by asce0** [comment]
I don't know, I just need to access GPT-4 bot

**Comment by canxin121** [comment]
It should work now.You could try again.
