### ISSUE TITLE
KeyError: 'chats'

### ISSUE THREAD

**Issue by lijiansu** [canxin121/Async-Poe-Client#17]
使用test.py文件函数直接运行，报错获取不到chat_code：Cell In[8], line 6
      4     text+=message
      5     await asyncio.sleep(3)
----> 6 chat_code = poe_client.bot_code_dict[name][0]
      7 async for message in poe_client.ask_stream(url_botname='ChatGPT', question="写1句诗词", chat_code=chat_code,suggest_able= False):
      8     print(message, end="")

File [c:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\async_poe_client\client.py:64](file:///C:/Users/Administrator/AppData/Local/Programs/Python/Python310/lib/site-packages/async_poe_client/client.py:64), in Poe_Client.bot_code_dict(self)
     62 @property
     63 def bot_code_dict(self):
---> 64     return {
     65         bot: [chat for chat in data["chats"]] for bot, data in self.bots.items()
     66     }

File [c:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\async_poe_client\client.py:65](file:///C:/Users/Administrator/AppData/Local/Programs/Python/Python310/lib/site-packages/async_poe_client/client.py:65), in (.0)
     62 @property
     63 def bot_code_dict(self):
     64     return {
---> 65         bot: [chat for chat in data["chats"]] for bot, data in self.bots.items()
     66     }

KeyError: 'chats'

**Comment by lijiansu** [comment]
无法在同一个对话中连续对话，每次都会新建对话

**Comment by canxin121** [comment]
这个上次好像已经修复了,你可以更新试试
