### ISSUE TITLE
错误信息：Failed to extract 'viewer' or 'user_id' from 'next_data'.

### ISSUE THREAD

**Issue by PoetGcc** [canxin121/Async-Poe-Client#2]
当我创建poe_client = await Poe_Client(token).create()时，会直接报错：

Failed to extract 'viewer' or 'user_id' from 'next_data'.

**Comment by canxin121** [comment]
使用最新版加代理

**Comment by PoetGcc** [comment]
> 使用最新版加代理

poe_client()不穿入代理不行吗？我的使用方式是打的本地docker镜像包，电脑挂了全局的代理

**Comment by canxin121** [comment]
win➕docker？不太确定，你可以试试直接本机运行，不用docker，试试能不能用。

**Comment by PoetGcc** [comment]
> win➕docker？不太确定，你可以试试直接本机运行，不用docker，试试能不能用。

我是mac+docker。服务器ubuntu+docker也不行

我本地直接运行，报错：

```
  File "/Users/gcc/PycharmProjects/anyc/ThePoe/ppi/my_ppi.py", line 7, in <module>
    from async_poe_client import Poe_Client
  File "/Users/gcc/PycharmProjects/anyc/ThePoe/venv/lib/python3.8/site-packages/async_poe_client/__init__.py", line 1, in <module>
    from .client import Poe_Client
  File "/Users/gcc/PycharmProjects/anyc/ThePoe/venv/lib/python3.8/site-packages/async_poe_client/client.py", line 26, in <module>
    class Poe_Client:
  File "/Users/gcc/PycharmProjects/anyc/ThePoe/venv/lib/python3.8/site-packages/async_poe_client/client.py", line 271, in Poe_Client
    async def send_query(self, query_name: str, variables: dict) -> Any | None:
TypeError: unsupported operand type(s) for |: '_SpecialForm' and 'NoneType'

```

**Comment by canxin121** [comment]
哦哦，这个是python版本问题，我不小心使用了一个新版本的特性

**Comment by PoetGcc** [comment]
> 哦哦，这个是python版本问题，我不小心使用了一个新版本的特性

我本地电脑是3.8，docker内使用的3.11

**Comment by canxin121** [comment]
确定p_b没问题的话，ping一下poe.com，看看能不能通

**Comment by PoetGcc** [comment]
> 确定p_b没问题的话，ping一下poe.com，看看能不能通

服务器是可以ping通的

**Comment by akl7777777** [comment]
poe官网好像又改了...

**Comment by PoetGcc** [comment]
> 现在还有这个问题吗?

抱歉老哥，我这两天太忙，没来得及再验证，等我两天不忙了，在验证下

**Comment by canxin121** [comment]
那先留着0.0

**Comment by Yc7521** [comment]
现在poe更新了，貌似接口无法使用了

**Comment by canxin121** [comment]
> 现在poe更新了，貌似接口无法使用了

<img width="856" alt="image" src="https://github.com/canxin121/Async-Poe-Client/assets/69547456/ab06e4b5-bb32-4259-ac60-b548eb8eaaef">
你自己该更新了吧,昨天我发版了
