### ISSUE TITLE
formkey是什么

### ISSUE THREAD

**Issue by ymyguang** [canxin121/Async-Poe-Client#3]
token已填写，但是formkey不知道是什么

**Comment by canxin121** [comment]
<img width="1238" alt="image" src="https://github.com/canxin121/Async-Poe-Client/assets/69547456/ec6a4fdf-51bb-4dce-b40e-9aeef3f16e8f">
图右边的formkey就是,上面写了获取方式

**Comment by ymyguang** [comment]
已解决感谢开发者，多问一句，这个截图是什么插件吗

**Comment by canxin121** [comment]
> 已解决感谢开发者，多问一句，这个截图是什么插件吗

spark gpt,也是我的项目.qq tg discord kook的通用语言模型机器人
