### ISSUE TITLE
TypeError: unsupported operand type(s) for |: '_SpecialForm' and 'NoneType'

### ISSUE THREAD

**Issue by henjicn** [canxin121/Async-Poe-Client#5]
gpt_wz.py:None (gpt_wz.py)
gpt_wz.py:1: in <module>
    from async_poe_client import Poe_Client
/usr/local/lib/python3.9/site-packages/async_poe_client/__init__.py:1: in <module>
    from .client import Poe_Client
/usr/local/lib/python3.9/site-packages/async_poe_client/client.py:28: in <module>
    class Poe_Client:
/usr/local/lib/python3.9/site-packages/async_poe_client/client.py:280: in Poe_Client
    async def send_query(self, query_name: str, variables: dict) -> Any | None:
E   TypeError: unsupported operand type(s) for |: '_SpecialForm' and 'NoneType'

环境为：Mac+Python 3.9

**Comment by canxin121** [comment]
我的我的，待会修复

**Comment by canxin121** [comment]
修好了,试下0.1.9版本
