### ISSUE TITLE
同一个提问因为重试会提问3次

### ISSUE THREAD

**Issue by 445022889** [canxin121/Async-Poe-Client#8]
我通过flask仅调用自己代码的命令一次，实际上每次都有，但是就是不返回
<img width="1193" alt="image" src="https://github.com/canxin121/Async-Poe-Client/assets/8262562/b988c114-9d74-410c-9ffb-aa0a6198e053">

<img width="1287" alt="image" src="https://github.com/canxin121/Async-Poe-Client/assets/8262562/3437b696-d36b-4922-a6f4-a973668ed28d">

<img width="556" alt="image" src="https://github.com/canxin121/Async-Poe-Client/assets/8262562/042f1264-d91a-42a6-afbc-79e28ed86889">

**Comment by canxin121** [comment]
可以试试现在啥情况,更新了

**Comment by canxin121** [comment]
> Error in .local/lib/python3.10/site-packages/async_poe_client/client.py", line 103, in get_basedata self.viewer = self.next_data['props']['initialData']['data']['pageQuery']['viewer'] TypeError: 'NoneType' object is not subscriptable

are you sure your p_b and form key are correct? try using a proxt

**Comment by phamxtien** [comment]
Sure p_b and form key.
When I print out self.next_data, it prints:

{'props': {'pageProps': {'data': {'viewer': {'uid': None, 'googleOauthState': 'eyJwZXJtcyI6ICIiLCAiY3NyZiI6ICJmYmRmNWVkNmJlMTc3MDg4NGEyNTc2M2E0NjI4OTYyZSIsICJwbGF0Zm9ybSI6ICJ3ZWIiLCAidGFyZ2V0IjogIiJ9', 'appleOauthState': 'eyJwZXJtcyI6ICIiLCAiY3NyZiI6ICJmYmRmNWVkNmJlMTc3MDg4NGEyNTc2M2E0NjI4OTYyZSIsICJwbGF0Zm9ybSI6ICJ3ZWIiLCAidGFyZ2V0IjogIiJ9', 'showEmailFirstOnPoeLoginPage': True, 'googleOneTapPromptInfo': {'isViewerEligibleToSeePrompt': True, 'isViewerEligibleForAutoLogin': True}, 'enableIosMweb': False, 'id': 'Vmlld2VyOjA='}}, 'queryVariables': {}, 'additionalProps': {}, 'uid': None}, 'initialProps': {'userAgent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36', 'theme': 'auto', 'middlewareStart': 1692349345318, 'i18nInstanceState': {'ns': ['translation'], 'lng': 'en'}}, 'initialData': None, '__N_SSP': True}, 'page': '/login', 'query': {}, 'buildId': 'q10dxdi9B7iRPBeMLpDDh', 'assetPrefix': 'https://psc2.cf2.poecdn.net/51dc8dc0d2f732ace7d35414570b130f47fcb3bb', 'isFallback': False, 'gssp': True, 'appGip': True, 'scriptLoader': []}
{'props': {'pageProps': {'data': {'viewer': {'uid': None, 'googleOauthState': 'eyJwZXJtcyI6ICIiLCAiY3NyZiI6ICIyZTIxNmQ5ZmYyZTI4MTY0MWYzNWU0ZTUyYWZjYmNjMiIsICJwbGF0Zm9ybSI6ICJ3ZWIiLCAidGFyZ2V0IjogIiJ9', 'appleOauthState': 'eyJwZXJtcyI6ICIiLCAiY3NyZiI6ICIyZTIxNmQ5ZmYyZTI4MTY0MWYzNWU0ZTUyYWZjYmNjMiIsICJwbGF0Zm9ybSI6ICJ3ZWIiLCAidGFyZ2V0IjogIiJ9', 'showEmailFirstOnPoeLoginPage': True, 'googleOneTapPromptInfo': {'isViewerEligibleToSeePrompt': True, 'isViewerEligibleForAutoLogin': True}, 'enableIosMweb': False, 'id': 'Vmlld2VyOjA='}}, 'queryVariables': {}, 'additionalProps': {}, 'uid': None}, 'initialProps': {'userAgent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36', 'theme': 'auto', 'middlewareStart': 1692349346306, 'i18nInstanceState': {'ns': ['translation'], 'lng': 'en'}}, 'initialData': None, '__N_SSP': True}, 'page': '/login', 'query': {}, 'buildId': 'q10dxdi9B7iRPBeMLpDDh', 'assetPrefix': 'https://psc2.cf2.poecdn.net/51dc8dc0d2f732ace7d35414570b130f47fcb3bb', 'isFallback': False, 'gssp': True, 'appGip': True, 'scriptLoader': []}
{'props': {'pageProps': {'data': {'viewer': {'uid': None, 'googleOauthState': 'eyJwZXJtcyI6ICIiLCAiY3NyZiI6ICIwMDg4N2M2NDhlMjQ2NWFlMDlhOWU3ZDEwZmNkOTkxNCIsICJwbGF0Zm9ybSI6ICJ3ZWIiLCAidGFyZ2V0IjogIiJ9', 'appleOauthState': 'eyJwZXJtcyI6ICIiLCAiY3NyZiI6ICIwMDg4N2M2NDhlMjQ2NWFlMDlhOWU3ZDEwZmNkOTkxNCIsICJwbGF0Zm9ybSI6ICJ3ZWIiLCAidGFyZ2V0IjogIiJ9', 'showEmailFirstOnPoeLoginPage': True, 'googleOneTapPromptInfo': {'isViewerEligibleToSeePrompt': True, 'isViewerEligibleForAutoLogin': True}, 'enableIosMweb': False, 'id': 'Vmlld2VyOjA='}}, 'queryVariables': {}, 'additionalProps': {}, 'uid': None}, 'initialProps': {'userAgent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36', 'theme': 'auto', 'middlewareStart': 1692349347557, 'i18nInstanceState': {'ns': ['translation'], 'lng': 'en'}}, 'initialData': None, '__N_SSP': True}, 'page': '/login', 'query': {}, 'buildId': 'q10dxdi9B7iRPBeMLpDDh', 'assetPrefix': 'https://psc2.cf2.poecdn.net/51dc8dc0d2f732ace7d35414570b130f47fcb3bb', 'isFallback': False, 'gssp': True, 'appGip': True, 'scriptLoader': []}

**Comment by phamxtien** [comment]
Sure p_b and form key
When print out self.next_data (after line 97 of client.py). It prints:

{'props': {'pageProps': {'data': {'viewer': {'uid': None, 'googleOauthState': 'eyJwZXJtcyI6ICIiLC..............', 'appleOauthState': 'eyJwZXJtcyI6ICIiLC..........', 'showEmailFirstOnPoeLoginPage': True, 'googleOneTapPromptInfo': {'isViewerEligibleToSeePrompt': True, 'isViewerEligibleForAutoLogin': True}, 'enableIosMweb': False, 'id': 'Vmlld2VyOjA='}}, 'queryVariables': {}, 'additionalProps': {}, 'uid': None}, 'initialProps': {'userAgent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36', 'theme': 'auto', 'middlewareStart': 1692349345318, 'i18nInstanceState': {'ns': ['translation'], 'lng': 'en'}}, 'initialData': None, '__N_SSP': True}, 'page': '/login', 'query': {}, 'buildId': 'q10dxdi9B7iRPBeMLpDDh', 'assetPrefix': 'https://psc2.cf2.poecdn.net/51dc8dc0d2f...............', 'isFallback': False, 'gssp': True, 'appGip': True, 'scriptLoader': []}

{'props': {'pageProps': {'data': {'viewer': {'uid': None, 'googleOauthState': 'eyJwZXJtcyI6ICIiLC..............', 'appleOauthState': 'eyJwZXJtcyI6ICIiLC..........', 'showEmailFirstOnPoeLoginPage': True, 'googleOneTapPromptInfo': {'isViewerEligibleToSeePrompt': True, 'isViewerEligibleForAutoLogin': True}, 'enableIosMweb': False, 'id': 'Vmlld2VyOjA='}}, 'queryVariables': {}, 'additionalProps': {}, 'uid': None}, 'initialProps': {'userAgent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36', 'theme': 'auto', 'middlewareStart': 1692349346306, 'i18nInstanceState': {'ns': ['translation'], 'lng': 'en'}}, 'initialData': None, '__N_SSP': True}, 'page': '/login', 'query': {}, 'buildId': 'q10dxdi9B7iRPBeMLpDDh', 'assetPrefix': 'https://psc2.cf2.poecdn.net/51dc8dc0d2f...............', 'isFallback': False, 'gssp': True, 'appGip': True, 'scriptLoader': []}

{'props': {'pageProps': {'data': {'viewer': {'uid': None, 'googleOauthState': 'eyJwZXJtcyI6ICIiLC..............', 'appleOauthState': 'eyJwZXJtcyI6ICIiLC..........', 'showEmailFirstOnPoeLoginPage': True, 'googleOneTapPromptInfo': {'isViewerEligibleToSeePrompt': True, 'isViewerEligibleForAutoLogin': True}, 'enableIosMweb': False, 'id': 'Vmlld2VyOjA='}}, 'queryVariables': {}, 'additionalProps': {}, 'uid': None}, 'initialProps': {'userAgent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36', 'theme': 'auto', 'middlewareStart': 1692349347557, 'i18nInstanceState': {'ns': ['translation'], 'lng': 'en'}}, 'initialData': None, '__N_SSP': True}, 'page': '/login', 'query': {}, 'buildId': 'q10dxdi9B7iRPBeMLpDDh', 'assetPrefix': 'https://psc2.cf2.poecdn.net/51dc8dc0d2f...............', 'isFallback': False, 'gssp': True, 'appGip': True, 'scriptLoader': []}

**Comment by canxin121** [comment]
` 'page': '/login'` it seems to say that you didn't login in. I assume your p_b is incorrect

**Comment by phamxtien** [comment]
Sorry, I get p_b and form key on quora.com instead poe.com.
Sorry again.

**Comment by phamxtien** [comment]
It runs smooth!
Thanks
