### ISSUE TITLE
Failed to sending query:availableBotsSelectorModalPaginationQuery,error:'errors'. (retry: 5/5)

### ISSUE THREAD

**Issue by boxter007** [canxin121/Async-Poe-Client#9]
When I create a poe_client , I got a error message:
Failed to sending query:availableBotsSelectorModalPaginationQuery,error:'errors'. (retry: 5/5)
Then I find the poe.com return message:
{"success":false,"message":"Bad Request"}

**Comment by canxin121** [comment]
check your formkey

**Comment by boxter007** [comment]
p-b is wrong
